# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = docs-build

# Put it first so that "make" without argument is like "make help".
help:
	@uv run $(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

clean:
	@uv run $(SPHINXBUILD) -M clean "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O);

deploy:
	@if [ -d "docs-build/html" ]; then \
	    echo "Removing existing worktree..."; \
	    git worktree remove -f docs-build/html; \
	fi
	@cd docs-build && git worktree add -f html gh-pages || true

doctest:
	@uv run sphinx-build -b doctest ./source ./docs-build/doctest

local:
	@uv run sphinx-apidoc -o source src/papertrail/ --separate ; uv run sphinx-build source docs-build/html

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@uv run $(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
